# Generated by Django 4.2.7 on 2026-01-19 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business name', max_length=100)),
                ('subdomain', models.CharField(help_text="Subdomain for business (e.g., 'salon' for salon.yourdomain.com)", max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')])),
                ('email', models.EmailField(help_text='Business contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('business_hours_start', models.TimeField(default='09:00', help_text='Business opening time')),
                ('business_hours_end', models.TimeField(default='18:00', help_text='Business closing time')),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=50)),
                ('email_from_name', models.CharField(help_text='Name shown in emails', max_length=100)),
                ('email_from_address', models.EmailField(blank=True, help_text='Custom from email (optional)', max_length=254)),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary brand color (hex)', max_length=7)),
                ('logo_url', models.URLField(blank=True, help_text='Logo URL (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address (used for login)', max_length=254, unique=True)),
                ('first_name', models.CharField(help_text='First name', max_length=50)),
                ('last_name', models.CharField(help_text='Last name', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('user_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('business_owner', 'Business Owner')], default='business_owner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, help_text='Business this user belongs to (null for super admins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.business')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('customer_email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text="Customer's phone number", max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special requests or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business this reservation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.business')),
                ('customer', models.ForeignKey(blank=True, help_text='Legacy field - will be removed after migration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='api_reserva_busines_81c733_idx'), models.Index(fields=['business', 'start_time'], name='api_reserva_busines_ba0bd4_idx'), models.Index(fields=['customer_email'], name='api_reserva_custome_8ca0fc_idx')],
            },
        ),
    ]
