# Generated by Django 4.2.7 on 2026-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='api_reserva_custome_8ca0fc_idx',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(blank=True, help_text="Customer's email address (optional)", max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(help_text="Customer's phone number", max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer_phone'], name='api_reserva_custome_4083bd_idx'),
        ),
    ]
