# Generated by Django 4.2.7 on 2026-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_reservation_api_reserva_custome_8ca0fc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo (PNG only)', null=True, upload_to='business_logos/'),
        ),
    ]
