# Generated by Django 4.2.7 on 2026-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_business_logo_url_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Logo URL (alternative to file upload)'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo (PNG file)', null=True, upload_to='business_logos/'),
        ),
    ]
