# Generated by Django 4.2.7 on 2026-03-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_business_logo_url_alter_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email_from_name',
            field=models.CharField(blank=True, help_text='Name shown in emails', max_length=100),
        ),
    ]
