# Generated by Django 4.2.7 on 2026-03-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_email_from_name_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rest_days', models.JSONField(blank=True, default=list, help_text="List of day integers (0=Mon, 6=Sun) when this staff member doesn't work")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='api.staff'),
        ),
    ]
