# Generated by Django 4.2.7 on 2026-04-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('barbershop', 'Barbershop'), ('salon', 'Salon'), ('clinic', 'Clinic'), ('other', 'Other')], default='other', help_text='Type of business', max_length=20),
        ),
    ]
